name: Datadog Integration

on:
  push:
    branches:
      - main

jobs:
  notify-datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Datadog about deployment
        run: |
          curl -X POST "https://api.datadoghq.eu/api/v1/events" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
          -d '{
          "series": [{
            "metric": "my.custom.metric",
            "points": [[$(date +%s), 1]],
            "type": "gauge",
            "tags": ["environment:production"]
          }]
          }
     
