name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up environment (Node.js, Python, etc.)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Enable Datadog CI Visibility with tracing
      - name: Send CI data to Datadog
        uses: datadog/ci-visibility-github-action@v2
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          service: github-ci-pipeline
          environment: production
          site: datadoghq.eu  # Use 'datadoghq.eu' for EU users
