name: Datadog Integration

on:
  push:
    branches:
      - main

jobs:
  notify-datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Datadog about deployment
        run: |
          curl -X POST "https://api.datadoghq.eu/api/v1/events" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
          -d '{
                "title": "Deployment Notification",
                "text": "A new deployment has been made to the main branch.",
                "priority": "normal",
                "tags": ["environment:production"]
              }'
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
